spring:
  application:
    name: "accounts"
build:
  version: "1.0.0"

accounts:
  message: "Hello from accounts service from prod"
  contactDetails:
    email: "cgnexus-prod@gmail.com"
    name: "CG Nexus Prod"
  onCallSupport:
    - (777) 777-7777
    - (888) 888-8888
