spring:
  application:
    name: cards

build:
  version: "1.0.0"

cards:
  message: "Hello from cards service from "
  contactDetails:
    email: "cgnexus-prod@gmail.com"
    name: "CG Nexus"
  onCallSupport:
    - (777) 777-7777
    - (888) 888-8888
